"""Initial Migration

Revision ID: 00671a72a9c0
Revises: b282e6094127
Create Date: 2021-08-17 16:22:54.650795

"""

# revision identifiers, used by Alembic.
revision = '00671a72a9c0'
down_revision = 'b282e6094127'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
