"""Initial Migration

Revision ID: 72d6e7c5d49f
Revises: 834cc5dc43bd
Create Date: 2021-08-19 16:13:53.609793

"""

# revision identifiers, used by Alembic.
revision = '72d6e7c5d49f'
down_revision = '834cc5dc43bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'post',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'post',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
