"""Initial Migration

Revision ID: 834cc5dc43bd
Revises: 00671a72a9c0
Create Date: 2021-08-17 16:59:56.221796

"""

# revision identifiers, used by Alembic.
revision = '834cc5dc43bd'
down_revision = '00671a72a9c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
