"""Initial Migration

Revision ID: b282e6094127
Revises: 24adf0acfd73
Create Date: 2021-08-17 16:05:56.244012

"""

# revision identifiers, used by Alembic.
revision = 'b282e6094127'
down_revision = '24adf0acfd73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
